#### My prediction for the code below is that it will import numpy and assign it to np

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

My prediction was correct

#### My prediction for the code below is that it will assign a three dimensional numpy array with the shape of (3, 4, 5), which each number in the array running from 0 to 9, to x

In [2]:
x = np.random.randint(10, size=(3, 4, 5))

My prediction was correct

#### My prediction for the code below is that it will return the numpy array x

In [3]:
x

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

My prediction was correct

#### My prediction for the code below is that it will return the number from the second table, third row, and fourth column position of the array x

In [4]:
x[1,2,3]

1

My prediction was correct

#### My prediction for the code below is that it will return a numpy array of the first two tables of the three dimensional numpy array x. Each table contains two rows start from the second row and end at the third row, and in each row, there are numbers start from index 1 and end before index 5 with the jump of 2 indexes

In [5]:
x[0:2, 1:3, 1:5:2]

array([[[3, 2],
        [6, 8]],

       [[0, 5],
        [3, 1]]])

My prediction was correct

#### My prediction for the code below is that it will retrieve from x and return a numpy array which contain 3 table, each table has 4 rows, and each row has the first number of its row

In [6]:
x[:,:, :1]

array([[[5],
        [9],
        [7],
        [6]],

       [[5],
        [3],
        [2],
        [3]],

       [[9],
        [3],
        [0],
        [8]]])

My prediction was correct

#### My prediction for the code below is that it will make a copy of x and assign it to x2

In [7]:
x2 = x[:2, :2]
x2[0, 0, 0] = 99
x

array([[[99,  0,  3,  3,  7],
        [ 9,  3,  5,  2,  4],
        [ 7,  6,  8,  8,  1],
        [ 6,  7,  7,  8,  1]],

       [[ 5,  9,  8,  9,  4],
        [ 3,  0,  3,  5,  0],
        [ 2,  3,  8,  1,  3],
        [ 3,  3,  7,  0,  1]],

       [[ 9,  9,  0,  4,  7],
        [ 3,  2,  7,  2,  0],
        [ 0,  4,  5,  5,  6],
        [ 8,  4,  1,  4,  9]]])

My prediction was incorrect. The result is that it is just making a view of x. The proof is that when we modify x2, it is reflected into x

#### My prediction for the code below is that it will make a copy of x and assign it to x2

In [8]:
x2 = x[:2, :2].copy()
x2[0, 0, 0] = 0
x

array([[[99,  0,  3,  3,  7],
        [ 9,  3,  5,  2,  4],
        [ 7,  6,  8,  8,  1],
        [ 6,  7,  7,  8,  1]],

       [[ 5,  9,  8,  9,  4],
        [ 3,  0,  3,  5,  0],
        [ 2,  3,  8,  1,  3],
        [ 3,  3,  7,  0,  1]],

       [[ 9,  9,  0,  4,  7],
        [ 3,  2,  7,  2,  0],
        [ 0,  4,  5,  5,  6],
        [ 8,  4,  1,  4,  9]]])

My prediction was correct

#### My prediction for the **reshape()** method below is that it will get all of the values from x and redistribute them into a 2D array with five rows and 10 columns. Then, return it

In [9]:
try:
    print(x.reshape(5,10))
except Exception as e:
    print(e)

cannot reshape array of size 60 into shape (5,10)


However, my prediction was incorrect. It throws error since 60 values in x can not be redistributed to a 2D array with five rows and 10 columns because the total amount of value that array can hold is 5 x 10 = 50

#### My prediction for the code below is that it will get all of the values from x and redistribute them into a 2D array with the shape of six rows and 10 columns. Then, print it out

In [10]:
print(x.reshape(6, 10))


[[99  0  3  3  7  9  3  5  2  4]
 [ 7  6  8  8  1  6  7  7  8  1]
 [ 5  9  8  9  4  3  0  3  5  0]
 [ 2  3  8  1  3  3  3  7  0  1]
 [ 9  9  0  4  7  3  2  7  2  0]
 [ 0  4  5  5  6  8  4  1  4  9]]


My prediction was correct

#### My prediction for the code below is that it will create a numpy array and fill it with number from 1 to 9, then assign it to m

In [11]:
m = np.arange(1, 10)
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

My prediction was correct

#### My prediction for the **concatenate()** method below is that it will concatenate two numpy array m and n

In [12]:
n = np.arange(10, 15)
np.concatenate([m, n])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

My prediction was correct

#### My prediction for the **concatenate()** method below is that it will throw error since o is not a numpy array

In [13]:
o = list(range(15,20))
np.concatenate([m, n, o])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

My prediction was incorrect. **concatenate()** method still concatenate m, n, o eventhough o is a list

#### My prediction for the code below is that it will concatenate two numpy array grid together and then return the result

In [14]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

My prediction was correct

#### My prediction for the code below is that it will concatenate the first row of two grids and concatenate the second row of two grids. Then, the result is returned

In [15]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

My prediction was correct

#### My prediction for the code below is that it will concatenate two numpy array grid together and then return the result, which is a numpy array with four other arrays

In [16]:
np.vstack([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

My prediction was correct

#### My prediction for the code below is that it will concatenate the first row of two grids and concatenate the second row of two grids. Then, the result is returned

In [17]:
np.hstack([grid, grid])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

My prediction was correct

#### My prediction for the code below is that it will split the numpy array m into m1, m2, and m3. The values of m1 is m from start to before index 2, m2 is m from index 2 to before in dex 5, m3 is m from after index 5. After that, the code print out m1, m2, and m3

In [18]:
m1, m2, m3 = np.split(m, [2, 5])
print(m1, m2, m3)

[1 2] [3 4 5] [6 7 8 9]


My prediction was correct

#### My prediction for the code below is that it will split the numpy array grid into two 2D arrays grid1 and grid2. The value of grid1 will be the first row of grid, and for grid2, the value will be the second row of grid. After that, the code print out grid1 and grid2

In [19]:
grid1, grid2 = np.vsplit(grid, [1])
print(grid1, grid2)

[[1 2 3]] [[4 5 6]]


My prediction was correct

#### My prediction for the code below is that it will split the numpy array grid into two 2D arrays grid1 and grid2. The value of grid1 will be the first column of grid, and for grid2, the value will be the second column of grid. After that, the code print out grid1 and grid2

In [20]:
grid1, grid2 = np.hsplit(grid, [1])
print(grid1, grid2)

[[1]
 [4]] [[2 3]
 [5 6]]


My prediction was correct

#### My prediction for the code below is that it will sum up all of the number in the numpy array and return the result

In [21]:
np.sum(m)

45

My prediction was correct

#### My prediction for the code below is that it will sum up all of the number in the 2D numpy array and return the result

In [22]:
np.sum(grid)

21

My prediction was correct

#### My prediction for the code below is that it will return the lowest value item from grid

In [23]:
np.min(grid)

1

My prediction was correct

#### My prediction for the code below is that it will return the highest value item from each row

In [24]:
grid.max(axis=0)

array([4, 5, 6])

My prediction was incorrect. The **max()** function in the code below return the highest value item from each column

#### My prediction for the code below is that it will return the highest value item from each row

In [25]:
grid.max(axis=1)

array([3, 6])

My prediction was correct

#### My prediction for the code below is that it will return the mean for each row

In [26]:
grid.mean(axis=1)

array([2., 5.])

My prediction was correct

#### My prediction for the code below is that it will print out numpy arrays n, o, and return the sum of both array

In [27]:
print('n array:', n)
print('o array:', o)
n + o

n array: [10 11 12 13 14]
o array: [15, 16, 17, 18, 19]


array([25, 27, 29, 31, 33])

My prediction was incorrect. The n + o return a numpy array that the value each index is the sum of the values of that index in n and o

#### My prediction for the code below is that it will return a numpy array that has the value is the sum of each number in n and 5

In [28]:
n + 5

array([15, 16, 17, 18, 19])

My prediction was correct

#### My prediction for the code below is that it will return a 2D numpy array that each row is an array contains numbers from 0 to 2

In [29]:
m = np.arange(3)[:, np.newaxis]
m

array([[0],
       [1],
       [2]])

My prediction was incorrect. The code above return a 2D numpy array that each row has one number and as we go down all the row, the values run from 0 to 2

#### My prediction for the code below is that it will return a 2D numpy array that has the amount of row is the amount of row in m, and the amount of column is the amount of number in n

In [30]:
m + n

array([[10, 11, 12, 13, 14],
       [11, 12, 13, 14, 15],
       [12, 13, 14, 15, 16]])

My prediction was correct

#### My prediction for the code below is that it will throw exception since the shape of o and m are not compatible to be broadcast together

In [31]:
try:
    o = np.array([[1, 2, 3], [4, 5, 6]])
    m + o
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (3,1) (2,3) 


My prediction was correct